# Generated by Django 2.2.7 on 2022-03-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220227_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBook',
        ),
    ]
