version: "3.1"

services:
  web:
      build: .
      command: gunicorn mebook_project.wsgi -b 0.0.0.0:8000                   
      environment:
        - ENVIRONMENT=development
        - SECRET_KEY=3!90pfr%rr=we&ghgdhc$_c7@bxdqsq5sos7zrvu67et745019
        - USE_S3=TRUE
        - AWS_ACCESS_KEY_ID=AKIAU4GQWWAGXLOWCPWK
        - AWS_SECRET_ACCESS_KEY=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
        - AWS_STORAGE_BUCKET_NAME=mebookhub
      volumes:
        - .:/code
      ports:
        - 8000:8000  
      depends_on:
        - db

  db:
    restart: always
    image: postgres:11
    container_name: db_postgres 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mebook_hub
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      depends_on:
        - db
      ports:
        - 5051:80
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: root
      restart: always

volumes:
    postgres_data: