# Generated by Django 2.2.7 on 2022-01-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('link_to_book', models.CharField(max_length=200)),
            ],
        ),
    ]
